#!/bin/sh

cat "$1" | perl -e '$/=undef;@src=<>;$src=join("\n",@src);print"print((function(){$src}).toString())"' > temp.js
js -f temp.js

# src = File.read(ARGV[0])
# src = "(function () { " + src + "}).toString()"
# src = `js`


