#!/bin/sh

NAME="lib"

PROJ_ROOT="/www/$NAME"
NGINX="/usr/local/nginx/sbin/nginx"
TYPE="$SERVER_TYPE"

if [ "$TYPE" = "" ]; then
	TYPE="developer"
fi


echo "Starting $NAME as $TYPE..."

$NGINX -c "$PROJ_ROOT/nginx.$TYPE.conf"
