#!/bin/sh

NAME="lib-0.3"

PROJ_ROOT="/www/$NAME"
NGINX="/usr/local/nginx/sbin/nginx"
TYPE="$SERVER_TYPE"

if [ "$TYPE" = "" ]; then
	TYPE="developer"
fi


echo "Stopping $NAME as $TYPE..."
# sending INT signal
if [ -f $PROJ_ROOT/nginx.pid ]; then
	kill -2 `cat $PROJ_ROOT/nginx.pid`
else
	echo "nginx was not started (no pid file found)"
fi